!!python/object:argparse.Namespace
add_trunk: false
air: null
alignunif: false
arbor_rare: false
arbor_val: false
augreg_trans: false
batch_size: 64
beta1: 0.9
beta2: 0.98
bioclip_rare: true
birds: null
byol: false
caption_subset: ''
clamp: 0
copy_codebase: false
csv_caption_key: title
csv_cleaned: false
csv_img_key: filepath
csv_scrambled: false
csv_separator: "\t"
dataset_resampled: false
dataset_type: auto
dc_eval: false
dc_eval_data_dir: null
dcl: false
ddp_static_graph: false
debug: false
dist_backend: nccl
dist_url: env://
downsample_trans: false
dry_run: false
ds_cipher: false
ds_filter: ''
elp: false
epochs: 32
eps: 1.0e-06
extended_metrics: true
filip: false
fine_tune: false
flowers: null
food: null
force_quick_gelu: false
fungi: true
gather_with_grad: false
gc: false
gpumaxbatch: 32
grad_checkpointing: false
grayscale: false
gsam: false
horovod: false
ideo: false
image_mean: null
image_size: 224
image_ssl_loss_weight: 0.05
image_std: null
imagenet_a: null
imagenet_r: null
imagenet_real: null
imagenet_s: null
imagenet_train: null
imagenet_tune_freq: 0
imagenet_v2: null
imagenet_val: null
img_weight: 0.5
inat2017: null
inat2018: null
inat2021: null
insecta: null
insects2: true
integer_labels: false
iqe: false
linear_probe: false
load_first_k: 0
local_loss: false
lock_image: false
lock_image_freeze_bn_stats: false
lock_image_unlocked_groups: 0
lock_text: false
log_local: false
logs: ./logs/
lr: 0.0005
lsuv: false
metacaptions: ''
mlm: false
model: ViT-B-16
multiclass: false
name: null
no_ensembling: false
no_set_device_rank: false
norm_gradient_clip: null
objectnet: null
openimages_val: null
precision: amp
pretrained: ''
pretrained_head: ''
pretrained_image: false
project: vlhub
ramping: false
report_to: ''
resume: /scratch/bf996/bioclip/bioclip-main/logs/2024_05_29-21_30_03-model_ViT-B-16-lr_0.0002-b_2048-j_8-p_bf16/checkpoints/epoch_8.pt
save_frequency: 1
save_most_recent: false
save_results_to_csv: ''
schema: null
seed: 0
shift_cipher: null
sim_clr: false
sim_clr_trans: false
simplecaptions: false
size_controlled: ''
skip_scheduler: false
stanfordcars: null
strict: false
taxon: common_name
text_ssl_loss_weight: 0.05
text_weight: 0.5
timm_classifier_head_size: -1
token_reduce: false
token_scrambled: false
token_strip: false
token_trunc: null
tokenizer_path: null
torchscript: false
trace: false
train_data: null
train_num_samples: null
use_bn_sync: false
val_data: null
val_frequency: 1
val_num_samples: null
verify: false
vssl: false
wandb_notes: ''
warmup: 10000
wd: 0.2
workers: 8
zeroshot_frequency: 1
zeroshot_scramble: false
zs_lower: false
zs_upper: false
